version: '3.1'
services:
  mysql:
    image: mysql:8.0.32
    container_name: despesas_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  api:
    container_name: despesas_api
    image: node:16
    restart: always
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      - DB_HOST=mysql
      - DB_NAME=despesas_app
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=3001
      - JWT_SECRET=façoUmaQuandoUsarORailway
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql